<?php

namespace AppBundle\Repository;

/**
 * AttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackRepository extends \Doctrine\ORM\EntityRepository
{
}
