<?php

namespace AppBundle\Repository;

/**
 * PokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends \Doctrine\ORM\EntityRepository
{
}
